# Generated by Django 2.1.5 on 2019-02-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_auto_20190217_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Image', max_length=100),
        ),
    ]
